# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  repo-token:
    description: "github token"
outputs:
  time: # id of output
    description: 'The time we greeted you'
  release-url:
    description: "some url"
runs:
  using: 'docker'
  image: 'my-docker-image'
  args:
    - ${{ inputs.repo-token }}
    - ${{ inputs.who-to-greet }}